### ISSUE TITLE
プロトタイプ

### ISSUE THREAD

**Issue by tissueMO** [himantyu-yuma/todo-stack#1]
- [x] 自室に置く
  - [x] PC・スマホ両方から追加できるようにする（Web）
- [x] 必要事項
  - [x] タスク名・所要時間（予定）・最終期限・優先順位
- [x] 段階的な通知をする
  - [x] 低：今日余裕あるからコレもやっとけ
  - [x] 中：そろそろヤバい（ここを逃すと後で痛い目に遭う）
  - [x] 高：今日逃したら完全アウト
- [x] 1日のキャパシティを定義できるようにする
  - [x] 今日やるべきタスク（中）を列挙してきて
  - [x] 優先順位順→所要時間が短い順に片づけていく
  - [x] それでもキャパシティに余裕があれば：次のタスクが（低）で表示←そんなに積極的には出さない
  - [x] キャパシティに余裕がなければ：（高）だけに絞って表示
- [x] 完了を記録できるようにする
  - [x] 進行中のものは数日にわたって表示される
- [x] 改善の余地のある設定は簡単に変更できるようにする
  - [x] キャパシティ、タスク（低）の出現頻度、所要時間の内部計算（リスク係数）

**Comment by tissueMO** [comment]
バックエンド残り作業
---

- 当日のタスクを表示する順序・フィルターの調整
  - 調整のため、サンプルデータが必要

**Comment by himantyu-yuma** [comment]
## 編集機能をどう実装するか
- 編集ボタン押したらフォームを埋める？
- それともリストをそのまま編集できるようにする？

**Comment by himantyu-yuma** [comment]
@tissueMO 
PUTリクエスト（編集）をすると、limitが必ず1970年になってしまうんですがこれは送るデータが良くないんでしょうか…

- 送ってるデータ
```
{_id: "604e2fd243b95b29e43529c6", name: "テスト", hours: 5, limit: "2020-03-20T00:00:00", priority: 1}
```
- セットされる日付
```
1970-01-19T08:11:02
```

**Comment by tissueMO** [comment]
@himantyu-yuma ごめんなさい、寝ぼけていたのか追加時と編集時で時刻の変換が違っているのが原因でした。  
修正したものをPR出したのでマージしておいてください！

**Comment by himantyu-yuma** [comment]
一通りの機能を実装完了
