### ISSUE TITLE
タスクの一覧が見辛い

### ISSUE THREAD

**Issue by himantyu-yuma** [himantyu-yuma/todo-stack#16]
タスクの一覧表示をリストにしているが、とても見辛い
tableにして各項目でそろえたほうがいいかも
（長いタスク名の時とか崩れないよう注意）

**Comment by tissueMO** [comment]
せっかくBootstrap使ってるし、col-系のクラス付けてグリッドレイアウトにするといいかも。

**Comment by himantyu-yuma** [comment]
divで分けちゃっていいですかね？

**Comment by tissueMO** [comment]
ごめん、撤回します。  
内容構造的にテーブルなのでテーブルで作っちゃうのがいいと思う！

※グリッドレイアウトはサイト全体のレイアウトに使うものなので今回はちょっと文脈がちがいました、、、

**Comment by himantyu-yuma** [comment]
テーブルにしてみたら意外と見やすかったけど、もう少し調整必要そう
- 所要時間と完了ボタンの幅はもう少し狭くていい
- 完了ボタンをもう少し左（期限側）に寄せたい
- ついでに、時間もぱっと見でわかる表記にしたい

**Comment by tissueMO** [comment]
- 完了ボタンの幅・左端寄せ
  - `btn-block` ＋ CSS列幅指定
- 所要時間の幅
  - CSS列幅指定

**Comment by himantyu-yuma** [comment]
優先度の高いやつをぱっと見でわかりやすくする
- 濃淡？
- グラフ？
