### ISSUE TITLE
タスクの絞り込み結果がおかしい

### ISSUE THREAD

**Issue by himantyu-yuma** [himantyu-yuma/todo-stack#17]
タスクの絞り込み結果を取得したとき、想定している結果とすこし異なる

（確認した事象）
期限が同じタスクをそれぞれ2時間と3時間で作成したとき、片方しか表示されず、他のタスクが終わってからでないと表示されない

**Comment by tissueMO** [comment]
スコアリングロジックに不備があったのが原因。

**Comment by tissueMO** [comment]
#20 にて解決済み。
